### ISSUE TITLE
CMS: 2016 data release checklist

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#124]
Checklist for the next release, to be discussed and approved. This is to start the preparations.
(see also old estimates from https://github.com/cernopendata/opendata.cern.ch/issues/2335)

- [ ] collision dataset list 
- [ ] MC data
- [ ] dataset for pileup
- [ ] pileup profile description in `/docs/cms-guide-pileup-simulation` (http://opendata.cern.ch/docs/cms-guide-pileup-simulation), 
- [ ] categorize MC
- [ ] check resources
- [ ] transfer 
- [ ] Global tags to /cvmfs
  - data: 
  - MC: 
- [ ] build records for the condition data
- [ ] json files for validated runs
- [ ] build a trigger menu table as in  http://opendata.cern.ch/record/1700
- [ ] data-taking configurations 
- [ ] dataset short description for the records see https://github.com/cernopendata/data-curation/pull/120
- [ ] trigger listings for PD
- [ ] MC provenance and configurations files
- [ ] luminosity 
- [ ] usage examples & documentation
  - new `/docs/cms-virtual-machine-2016` ? 
  - new `/docs/cms-getting-started-2016` for NanoAOD
  - updates in `/docs/cms-guide-docker`
  - updates in `docs/about-cms` 
  - updates in `docs/cms-guide-for-condition-database`
