### ISSUE TITLE
CMS: 2012 final release checklist

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#126]
Checklist for the release of remaining pp 2012 data,  approved at the June/July CB. This is to start the preparations.
(see also the volume estimates in https://indico.cern.ch/event/1029215/contributions/4324588/attachments/2234005/3786244/DPOA_news_27_04_2021.pdf#page=5)

- [x] collision dataset list, see #130 
  - Run2012B (26 datasets) and Run2012C (26 datasets) already released: [portal records](http://opendata.cern.ch/search?page=1&size=20&type=Dataset&subtype=Collision&year=2012&experiment=CMS&file_type=aod)
  - Run2012A: 21 datasets in [das search](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2FRun2012A-22Jan2013*%2FAOD)
  - Run2012D: 26 dataset in [das search](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2FRun2012D-22Jan2013*%2FAOD)
- [x] MC data: released already 
  - [portal records](http://opendata.cern.ch/search?page=1&size=20&type=Dataset&subtype=Simulated&year=2012&experiment=CMS)
  - including ["on-demand" records](http://opendata.cern.ch/search?page=1&size=20&type=Dataset&subtype=Simulated&year=2012&experiment=CMS&ondemand=True)
- [x] dataset for pileup: released already 
   - [portal record](http://opendata.cern.ch/search?page=1&size=20&type=Dataset&subtype=Simulated&year=2012&experiment=CMS&file_type=gen-sim)
- [x] pileup profile description: already  in `/docs/cms-guide-pileup-simulation` (http://opendata.cern.ch/docs/cms-guide-pileup-simulation), 
- [x] categorize MC: done already
- [x] check resources
- [x] transfer see #149 
- [x] Global tags to /cvmfs: same as the already released 2012 data
- [x] build records for the condition data
  - [portal records](http://opendata.cern.ch/search?page=1&size=20&q=&subtype=Condition&type=Environment&year=2012)
- [x] json files for validated runs - update description
  - [portal record](http://opendata.cern.ch/record/1002) https://github.com/cernopendata/opendata.cern.ch/pull/3286
- [x] update build a trigger menu table to the full run range
  - [portal record](http://opendata.cern.ch/record/1701) 
  - check why the table is not in the order of run range, see https://github.com/cernopendata/opendata.cern.ch/issues/3283
  - data-curation input has them all https://github.com/cernopendata/data-curation/blob/master/cms-2012-collision-datasets/inputs/hlt-trigger-information.txt (50 lines)
- [x] data-taking configurations 
  - check if already on eospublic ( `eos ls -l /eos/opendata/cms/configuration-files/2012/cda*` has 48 files)
  - see https://github.com/cernopendata/opendata.cern.ch/issues/3283
- [x] dataset short description for the records 
  - initial draft in https://github.com/cernopendata/data-curation/pull/152
  - check with the actual trigger listings if any changes w.r.t. Run2012B/Run2012C
- [x] trigger listings for PD 
   - from the same file as for already released 2012 data
- [x] build records for datasets, see #151 
- [x] MC provenance and configurations files
   - decide if an update is doable to include generator parameters for the LHE step for all records
- [x] luminosity https://github.com/cernopendata/opendata.cern.ch/issues/3287
- [x] usage examples & documentation
  - any in `/docs/cms-virtual-machine-2011` ? No
  - updates in `/docs/cms-guide-docker` ? Updates for vnc pwd see https://github.com/cernopendata/opendata.cern.ch/issues/3289
  - updates in `docs/about-cms`  ? No
  - updates in `docs/cms-guide-for-condition-database` ?
    - https://github.com/cernopendata/opendata.cern.ch/issues/3290
    - https://github.com/cernopendata/opendata.cern.ch/issues/3291
- [x] news
