### ISSUE TITLE
CMS - HI 2013 release checklist

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#129]
- [x] Samples to release
  - HI data: #136 
  - pp reference 5.02 TeV 2015: #139 
    - see also 2013 2.76 pp ref from 2013: #140
  - MC: #138
- [x] transfers: #150 
- [x] CMSSW version and container
  - CMSSW version, see: #144
  - containers, see: #147
- [x] GT and copy to cvmfs / eospublic
  - GT, see #144 
- [x] json files for validated data
  - see #145 
- [x] data-curation directories, see #158
- [x] short dataset descriptions, see #165 
- [x] data-taking trigger menus, see #159, see https://github.com/cernopendata/opendata.cern.ch/issues/3376
- [x] trigger path listings, see #164
- [x] trigger path snippets, see #178
- [x] dataset provenance, see #168
- [x] luminosity, see #146
- [x] usage examples, see #175 

Updates to docs:

- [x] condition data guide, see https://github.com/cernopendata/opendata.cern.ch/issues/3396
- [x] docker instructions see https://github.com/cernopendata/opendata.cern.ch/issues/3373
- [x] getting started with HI data, see https://github.com/cernopendata/opendata.cern.ch/issues/3397
