### ISSUE TITLE
CMS: 2017 release checklist

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#245]
Checklist for the 2017 data release

- [ ] collision dataset list
- [ ] MC dataset list
- [ ] approval
- [ ] resources
- [ ] transfer
- [ ] build collision dataset records
     - [ ] datataking configs
     - [ ] HLT trigger lists
     - [ ] dataset short descriptions 
- [ ] build MC dataset records
- [ ] pileup record
- [ ] produce PFNANO
- [ ] build the PFNANO dataset records
- [ ] GT for MC
   - [ ] transfer to eospublic
   - [ ] build records 
- [ ] test VM
- [ ] test container 
- [ ] luminosity
- [ ] corrections
- [ ] update docs
   - [ ] docker guide
   - [ ] condition db guide
   - [ ] getting started miniaod (minimal changes)
   - [ ] getting stated nanoaod (minimal changes if any)

**Comment by jmhogan** [comment]
For the cross-section tasks (@danaalsharif):

This is the script that adds them to the records I believe: https://github.com/cernopendata/data-curation/blob/master/utils/update_fixtures_cross_sections.py

I believe the files are located here but I can't currently access this folder on lxplus: `/eos/user/s/sxiaohe/OpenData/MC2016/`. Hopefully @Ari-mu-l can check who has access to those files and can comment whether these folders of 2016 cross sections need to be copied to a certain local path in order to run the cross section update script. The production of the cross section files is documented here: https://github.com/Ari-mu-l/OpenData

The idea is that 2016 and 2017 share ~most samples. For example: 
 * from Kati's [2017 MC list](https://github.com/cernopendata/data-curation/issues/247), this MiniAOD: /DY1jToLL_M-1to10_Pt-0to70_TuneCP5_13TeV-madgraph-pythia8
 * matches [this record for 2016](https://opendata.cern.ch/record/35524): /DY1jToLL_M-1to10_Pt-0to70_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
 * The string between the first two `/` symbols is the same, the difference between 2016 and 2017 comes later. I believe that only the first (matching) part of the name is used to identify the right cross section file.

Goal is to use the portion of the name is that is synchronous to re-use 2016 cross-sections for 2017 records, and to only compute new cross sections for 2017 samples without a 2016 match.

**Comment by clelange** [comment]
If the cross-section tasks has been abandoned, I can look into it in a couple of weeks. I would set up a mechanism to run the GenXsecAnalyzer automatically over a list of samples. Let me know.

**Comment by Ari-mu-l** [comment]
I am no longer working on the cross section tasks, but please let me know if you would need access to certain folders.
