### ISSUE TITLE
CMS: 2011 RunB dataset release checklist

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#64]
Checklist for the release

- [x] dataset list [ `/*/Run2011B-12Oct2013*/AOD`](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*Run2011B-12Oct2013*%2FAOD) Size [96.3TB](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=block+dataset%3D%2F*%2F*Run2011B-12Oct2013*%2FAOD+%7C+sum%28block.size%29)
   - see #87 for ZeroBias
- [x] transfer
   - see #81 
- [x] check that all trigger menus are in http://opendata.cern.ch/record/1700 see #80
  - verify dataset ranges from DAS
  - check that all necessary files have been extracted and upload them in a new directory i https://github.com/cernopendata/data-curation/tree/master/cms-2011-collision-datasets/inputs
- [x] dataset short description for the records
   - can be taken as those in Run2011A
- [x] trigger listing from https://fwyzard.web.cern.ch/fwyzard/hlt/2011/dataset
   - already available in https://github.com/cernopendata/data-curation/blob/master/cms-2011-collision-datasets/inputs/fwyzard-hlt-2011-dataset.txt
- [x] provenance and configurations file
   - NB [cms-2011-collision-datasets](https://github.com/cernopendata/data-curation/tree/master/cms-2011-collision-datasets) is old HTML  and [cms-2012-collision-datasets](https://github.com/cernopendata/data-curation/tree/master/cms-2012-collision-datasets) is new json

```
/ZeroBias/Run2011B-12Oct2013-v1/AOD
/TauPlusX/Run2011B-12Oct2013-v1/AOD
/Tau/Run2011B-12Oct2013-v1/AOD
/SingleMu/Run2011B-12Oct2013-v1/AOD
/SingleElectron/Run2011B-12Oct2013-v1/AOD
/PhotonHad/Run2011B-12Oct2013-v1/AOD
/Photon/Run2011B-12Oct2013-v1/AOD
/MultiJet/Run2011B-12Oct2013-v1/AOD
/MuOnia/Run2011B-12Oct2013-v1/AOD
/MuHad/Run2011B-12Oct2013-v1/AOD
/MuEG/Run2011B-12Oct2013-v1/AOD
/MinimumBias/Run2011B-12Oct2013-v1/AOD
/MET/Run2011B-12Oct2013-v1/AOD
/Jet/Run2011B-12Oct2013-v1/AOD
/HT/Run2011B-12Oct2013-v1/AOD
/ForwardTriggers/Run2011B-12Oct2013-v1/AOD
/ElectronHad/Run2011B-12Oct2013-v1/AOD
/DoubleMu/Run2011B-12Oct2013-v1/AOD
/DoubleElectron/Run2011B-12Oct2013-v1/AOD
/BTag/Run2011B-12Oct2013-v1/AOD
```
