### ISSUE TITLE
CMS: 2015 data release checklist

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#65]
Checklist for the 2015 release, to be discussed and approved. This is to start the preparations.
(from https://github.com/cernopendata/opendata.cern.ch/issues/1310)

- [x] collision dataset list (~see #66~, change to Run2015D, see #70) 117.1 TB (AOD) + 15 TB (MiniAOD)
    - see [the final comment](https://github.com/cernopendata/data-curation/issues/70#issuecomment-578096213) and [the list](https://docs.google.com/document/d/1kgv_ch2AFz1FHdSmgX2WsYflry_DNN7pfNcXUGGtVnc/edit#heading=h.64v9utedgl4k) approved in Feb 2020
      - part (or all )of AOD: [`dataset=/*/Run2015D-16Dec2015-*/AOD`](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2FRun2015D-16Dec2015-*%2FAOD)
      - part (or all) of MINIAOD: [`dataset=/*/Run2015D-16Dec2015-*/MINIAOD`](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2FRun2015D-16Dec2015-*%2FMINIAOD)
         - https://twiki.cern.ch/twiki/bin/view/CMS/PdmV2015Analysis
      - but DoubleEG, SingleElectron from [`dataset=/*/*2015D*Jun2016/AOD`](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*2015D*Jun2016*%2FAOD) and  [`dataset=/*/*2015D*Jun2016*/MINIAOD`](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*2015D*Jun2016*%2FMINIAOD)
       - https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVDataReprocessing765p1EcalCorrFix
    - Records, see #https://github.com/cernopendata/opendata.cern.ch/issues/3153
- [x] MC data
   - Run2 Fall15 MiniAOD v2 campaign (76X version 2): [`dataset=/*/*RunIIFall15MiniAODv2-PU25nsData2015v1*/*`](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*RunIIFall15MiniAODv2-PU25nsData2015v1*%2F*) Size: 227.4TB, 7114 datasets
- [x] dataset for pileup, see #101
- [x] pileup profile description in `/docs/cms-guide-pileup-simulation` (http://opendata.cern.ch/docs/cms-guide-pileup-simulation), see https://github.com/cernopendata/opendata.cern.ch/issues/3162
- [x] categorize MC, check the categories, and decide the datasets to transfer (SM, B-phys, Higgs?), see #69 
   - transfer all as MINIAODSIM
- [x] check resources for the total of 360TB
- [x] setup the transfer with rucio (incl. proper book-keeping for MC), see #98 for test
- [x] transfer see #98
- [x] Global tags see #103
  - are they needed for MiniAOD? Not necessarily but for DP and MC generation
  - data: 76X_dataRun2_16Dec2015_v0
  - MC: 76X_mcRun2_asymptotic_RunIIFall15DR76_v1
- [x] build records for the condition data, see https://github.com/cernopendata/opendata.cern.ch/issues/3173
- [x] json files, see #104
- [x] build a trigger menu as in  http://opendata.cern.ch/record/1700 , see #67 
    - https://fwyzard.web.cern.ch/fwyzard/hlt/2015/summary
    - https://fwyzard.web.cern.ch/fwyzard/hlt/2015/summary.html
- [x] dataset short description for the records see https://github.com/cernopendata/data-curation/pull/120
- [x] trigger listing,  see #71
- [x] MC provenance and configurations file see #68 and #97
- [x] data-taking configurations see https://github.com/cernopendata/data-curation/issues/67#issuecomment-584044739 and #79
- [x] usage examples & documentation
  - new `/docs/cms-virtual-machine-2015` see https://github.com/cernopendata/opendata.cern.ch/issues/3164
  - new `/docs/cms-getting-started-2015` see https://github.com/cernopendata/opendata.cern.ch/issues/3165
  - updates in `/docs/cms-guide-docker` see https://github.com/cernopendata/opendata.cern.ch/issues/3163
  - updates in `docs/about-cms` see https://github.com/cernopendata/opendata.cern.ch/issues/3176
  - updates in `docs/cms-guide-for-condition-database` see https://github.com/cernopendata/opendata.cern.ch/issues/3172
