### ISSUE TITLE
CMS - HI release checklist

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#72]
Checklist for the HI release

- [x] dataset list see:
   - Release proposal: https://docs.google.com/document/d/1HpyhQQDg67bRknIryHR34xPvYy88NsUpPCNfD_pDzKk/edit#heading=h.baay3hopa6de
   - Listing from HI conveners: https://docs.google.com/spreadsheets/d/18TCtxtMYN_KmLIDhfoGB5m1prmgh6_WtKEudej3s56E/edit#gid=0
- [x] transfer
  - start with /HIHighPt/HIRun2011-15Apr2013-v1/RECO
  - see #73	
- [x] find out the GTs and make them available on /cvmfs/cms-opendata-conddb.cern.ch/
  - see #75		
- [x] confirm CMSSW versions and build containers 
  - https://cmssw-docker.web.cern.ch/
- [x] check if the HI trigger menus are available in (see #77)
   - in http://opendata.cern.ch/record/1699 for 2010 
   - in http://opendata.cern.ch/record/1700 for 2011
- [x] dataset short description for the records
- [x] trigger listings (see #82):
   - are not in https://fwyzard.web.cern.ch/fwyzard/hlt/2010/dataset
   - can be found in https://fwyzard.web.cern.ch/fwyzard/hlt/2011/dataset
- [x] provenance and reco configurations file see #78
- [x] usage examples and instructions see #76
- [x] json list for good runs and lumis (**tbc**) see #85
- [ ] luminosity, see #86
- [x] update for RECO format in http://opendata.cern.ch/docs/about-cms
- [x] update condition data guide http://opendata.cern.ch/docs/cms-guide-for-condition-database
- [x] update docker instruction page http://opendata.cern.ch/docs/cms-guide-docker

**Comment by katilp** [comment]
See the items to be addressed in #94
