### ISSUE TITLE
CMS: ML release checklist

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#91]
Release guidelines; see https://twiki.cern.ch/twiki/bin/view/CMS/DPOAMLSampleReleaseGuidelines

## Agreements
- [ ] the ML group agrees that  these samples are of interest for a public release
   - presented/discussed in (meeting/presentation link)
- [ ] the relevant POGs/PAGs and physics coordination agrees that these samples, their parent datasets and workflows to produce them can be brought into the public domain
  - presented/discussed in (meeting/presentation link)
- [ ] CB approval

## Parent dataset (if not already public data)
- [ ] identify the exact parent dataset (link in DAS)
- [ ] provenance (link to McM)
- [ ] create a CODP record (example  http://opendata.cern.ch/record/12201)
  - in https://github.com/cernopendata/opendata.cern.ch/tree/master/cernopendata/modules/fixtures/data/records
  - with name cms-simulated-datasets-Phase2-datascience.json (or add to ...Run2... if Run2 datasets)
- [ ] transfer to T3_CH_CERN_OpenData 

## ML sample production
- [ ] CMSSW version and OS for ML sample production? Check if a corresponding docker container is available in https://cmssw-docker.web.cern.ch/available-images , if not request
- [ ] is a GT is needed to produce the ML sample? If yes, have it transferred as sqlite files in /cvmfs/cms-opendata-conddb.cern.ch/
- [ ] make the ML sample production workflow available in a repository in https://github.com/cms-opendata-analyses, call it [DescriptiveName]ProducerTool
  - https://github.com/cms-opendata-analyses/TrackerRecHitProducerTool
- [ ] make sure that the ML production workflow runs in the CMS Open data environment (docker container of the CMS Open Data VM)
- [ ] Add a test workflow as a github action
- [ ] Create the corresponding CODP record for the production workflow (example http://opendata.cern.ch/record/12210)
  - in https://github.com/cernopendata/opendata.cern.ch/tree/master/cernopendata/modules/fixtures/data/records
  - with name cms-tools-Phase2-datascience.json (or add to ...Run2..., if Run2 samples)

## ML sample file
- [ ] produce the files
- [ ] upload them to /eos/opendata/cms/upload
- [ ] prepare the CODP record (example http://opendata.cern.ch/record/12220)
  - in https://github.com/cernopendata/opendata.cern.ch/tree/master/cernopendata/modules/fixtures/data/records
  - with name cms-derived-Phase2-datascience.json (or add it to ...Run2... if Run2 data)

## ML sample usage example
- [ ] prepare a usage example, reading the ML samples from the eospublic, runnable in the CMS Open Data environemnt
- [ ] have the example available in a repository in https://github.com/cernopendata-datascience
